# .goreleaser.yml

project_name: telee

env:
  - GO111MODULE=on

# Build destination
github_urls:
  # set to true if you use a self-signed certificate
  skip_tls_verify: false

before:
  hooks:
    - go mod tidy

builds:
  - main: cmd/main.go
    id: telee
    binary: telee
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    asmflags:
      - all=-trimpath=.
    gcflags:
      - all=-trimpath=.

archives:
  - name_template: '{{ .ProjectName }}-v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

release:
  prerelease: auto

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}_checksums.txt"
