name: actionlint

on:
  push:
    paths:
      - ".github/workflows/**"
  pull_request:
    paths:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  actionlint:
    uses: umatare5/common/.github/workflows/actionlint.yml@9056df6d56f55ebb1866ecb9cd24b6153e5a19f8 # v0.21.1
