name: actionlint

on:
  push:
    paths:
      - ".github/workflows/**"
  pull_request:
    paths:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  actionlint:
    uses: umatare5/common/.github/workflows/actionlint.yml@3df623d482350006c12656381399db14f8879fcc # v0.19.0
