name: actionlint

on:
  push:
    paths:
      - ".github/workflows/**"
  pull_request:
    paths:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  actionlint:
    uses: umatare5/common/.github/workflows/actionlint.yml@2dc181f4ceb6cd36a063f968d42c22953b554efd # v0.22.0
