name: Release Snapshot

on:
  schedule:
    - cron: "0 2 * * 1" # every Monday at 2:00

permissions:
  contents: read

jobs:
  snapshot:
    uses: umatare5/common/.github/workflows/go-release-snapshot.yml@9056df6d56f55ebb1866ecb9cd24b6153e5a19f8 # v0.21.1
    with:
      go_version: "1.27.1"
      goreleaser_version: "v2.18.2"
