name: Release Application

on:
  push:
    branches: [ "main" ]
    paths: [ "VERSION" ]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  tagging:
    uses: umatare5/common/.github/workflows/tagging.yml@ec6477148fb47ffc8b34a89dfdc2ec725a82863a # v0.18.0

  release:
    uses: umatare5/common/.github/workflows/go-release.yml@ec6477148fb47ffc8b34a89dfdc2ec725a82863a # v0.18.0
    with:
      go_version: "1.25.2"
      goreleaser_version: "v2.11.1"
