name: Release Snapshot

on:
  schedule:
    - cron: "0 2 * * 1" # every Monday at 2:00

permissions:
  contents: read

jobs:
  snapshot:
    uses: umatare5/common/.github/workflows/go-release-snapshot.yml@2dc181f4ceb6cd36a063f968d42c22953b554efd # v0.22.0
    with:
      go_version: "1.27.1"
      goreleaser_version: "v2.18.2"
