name: Release Application

on:
  push:
    branches: [ "main" ]
    paths: [ "VERSION" ]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  tagging:
    uses: umatare5/common/.github/workflows/tagging.yml@3df623d482350006c12656381399db14f8879fcc # v0.19.0

  release:
    needs: tagging
    uses: umatare5/common/.github/workflows/go-release.yml@3df623d482350006c12656381399db14f8879fcc # v0.19.0
    with:
      go_version: "1.27.1"
      goreleaser_version: "v2.18.0"
