name: Format and Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  fmt:
    uses: umatare5/common/.github/workflows/go-test-fmt.yml@8044b3c0ce0dce6411ec179c3ec0e675219c117f # v0.21.0
    with:
      go_version: "1.27.1"
      golangci_lint_version: "v2.13.2"
      golangci_lint_config: ".golangci.yml"
