name: Test and Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 2 * * 1" # every Monday at 2:00

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  build:
    uses: umatare5/common/.github/workflows/go-test-build.yml@8044b3c0ce0dce6411ec179c3ec0e675219c117f # v0.21.0
    with:
      go_version: "1.27.1"
