name: Test and Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    uses: umatare5/common/.github/workflows/go-test-build.yml@27d895ee9f1410471625dd66c22c0d63bb84b3b7 # v0.13.0
    with:
      go_version: "1.25.2"
