name: Test and Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 2 * * 1" # every Monday at 2:00

permissions:
  contents: read

jobs:
  build:
    uses: umatare5/common/.github/workflows/go-test-build.yml@2dc181f4ceb6cd36a063f968d42c22953b554efd # v0.22.0
    with:
      go_version: "1.27.1"
