name: govulncheck

on:
  push:
    branches: ["main"]
    paths:
      - "go.mod"
      - "go.sum"
      - "**.go"
      - ".github/workflows/go-vulncheck.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "go.mod"
      - "go.sum"
      - "**.go"
      - ".github/workflows/go-vulncheck.yml"
  schedule:
    - cron: "30 2 * * 1" # every Monday at 2:30, after the coverage run

permissions:
  contents: read

jobs:
  go-vulncheck:
    uses: umatare5/common/.github/workflows/go-vulncheck.yml@9056df6d56f55ebb1866ecb9cd24b6153e5a19f8 # v0.21.1
