name: Link Check

on:
  push:
    paths:
      - "**/*.md"
      - "lychee.toml"
      - ".github/workflows/lychee.yml"
  pull_request:
    paths:
      - "**/*.md"
      - "lychee.toml"
      - ".github/workflows/lychee.yml"

permissions:
  contents: read

jobs:
  lychee:
    uses: umatare5/common/.github/workflows/lychee.yml@9056df6d56f55ebb1866ecb9cd24b6153e5a19f8 # v0.21.1
    with:
      lychee_version: "v0.24.2"
