name: Link Check

on:
  push:
    paths:
      - "**/*.md"
      - "lychee.toml"
      - ".github/workflows/lychee.yml"
  pull_request:
    paths:
      - "**/*.md"
      - "lychee.toml"
      - ".github/workflows/lychee.yml"

permissions:
  contents: read

jobs:
  lychee:
    uses: umatare5/common/.github/workflows/lychee.yml@8044b3c0ce0dce6411ec179c3ec0e675219c117f # v0.21.0
    with:
      lychee_version: "v0.24.2"
