name: markdownlint

on:
  push:
    paths:
      - "**/*.md"
      - ".markdownlint-cli2.jsonc"
      - ".github/workflows/markdownlint.yml"
  pull_request:
    paths:
      - "**/*.md"
      - ".markdownlint-cli2.jsonc"
      - ".github/workflows/markdownlint.yml"

permissions:
  contents: read

jobs:
  markdownlint:
    uses: umatare5/common/.github/workflows/markdownlint.yml@9056df6d56f55ebb1866ecb9cd24b6153e5a19f8 # v0.21.1
