name: markdownlint

on:
  push:
    paths:
      - "**/*.md"
      - ".markdownlint-cli2.jsonc"
      - ".github/workflows/markdownlint.yml"
  pull_request:
    paths:
      - "**/*.md"
      - ".markdownlint-cli2.jsonc"
      - ".github/workflows/markdownlint.yml"

permissions:
  contents: read

jobs:
  markdownlint:
    uses: umatare5/common/.github/workflows/markdownlint.yml@2dc181f4ceb6cd36a063f968d42c22953b554efd # v0.22.0
